List<String> popularAthletes = [
  "LeBron James - NBA",
  "Patrick Mahomes - NFL",
  "Mike Trout - MLB",
  "Serena Williams - WTA",
  "Megan Rapinoe - NWSL",
  "Giannis Antetokounmpo - NBA",
  "Tom Brady - NFL",
  "Mookie Betts - MLB",
  "Naomi Osaka - WTA",
  "Christian Pulisic - MLS",
  "Kevin Durant - NBA",
  "Lamar Jackson - NFL",
  "Fernando Tatis Jr. - MLB",
  "Novak Djokovic - ATP",
  "Alex Morgan - NWSL",
  "Luka Dončić - NBA",
  "Russell Wilson - NFL",
  "Cody Bellinger - MLB",
  "Ashleigh Barty - WTA",
  "Chris Paul - NBA",
  "Aaron Judge - MLB",
  "De'Aaron Fox - NBA",
  "Saquon Barkley - NFL",
  "Simone Biles - USA Gymnastics",
  "Justin Herbert - NFL",
  "Justin Thomas - PGA",
  "Nneka Ogwumike - WNBA",
  "Trevor Lawrence - NFL",
  "Bryson DeChambeau - PGA",
  "Zion Williamson - NBA",
];
