import 'package:fantasy_athlete_stock_exchange/athlete.dart';

List<Athlete> popularAthletes = [
  Athlete("Aaron Judge", "MLB"),
  Athlete("Alex Morgan", "NWSL"),
  Athlete("Ashleigh Barty", "WTA"),
  Athlete("Bryson DeChambeau", "PGA"),
  Athlete("Chris Paul", "NBA"),
  Athlete("Christian Pulisic", "MLS"),
  Athlete("Cody Bellinger", "MLB"),
  Athlete("De'Aaron Fox", "NBA"),
  Athlete("Fernando Tatis Jr.", "MLB"),
  Athlete("Giannis Antetokounmpo", "NBA"),
  Athlete("Justin Herbert", "NFL"),
  Athlete("Justin Thomas", "PGA"),
  Athlete("Kevin Durant", "NBA"),
  Athlete("Lamar Jackson", "NFL"),
  Athlete("LeBron James", "NBA"),
  Athlete("Luka Dončić", "NBA"),
  Athlete("Megan Rapinoe", "NWSL"),
  Athlete("Mike Trout", "MLB"),
  Athlete("Mookie Betts", "MLB"),
  Athlete("Naomi Osaka", "WTA"),
  Athlete("Nneka Ogwumike", "WNBA"),
  Athlete("Novak Djokovic", "ATP"),
  Athlete("Patrick Mahomes", "NFL"),
  Athlete("Russell Wilson", "NFL"),
  Athlete("Saquon Barkley", "NFL"),
  Athlete("Serena Williams", "WTA"),
  Athlete("Simone Biles", "USA Gymnastics"),
  Athlete("Tom Brady", "NFL"),
  Athlete("Trevor Lawrence", "NFL"),
  Athlete("Zion Williamson", "NBA"),
];
